development:
  adapter: postgresql
  database: bacyla_development
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: whoop

test:
  adapter: postgresql
  database: <%= ENV['DATABASE'] || 'bacyla_test' %>
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: whoop

staging:
  adapter: postgresql
  database: bacyla_staging
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: whoop
