# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03cf9c8727d3460f505efa7db4937836f2435a8e5cb59a2b0955d665b199754c362f85f95e6c3f71d73ccfa741e48b6fcaae3e37d3231a5a5e9ea5d57e33b825

test:
  secret_key_base: 07793f1651286324ac9faba39d744b73782347f96abb28f40da20ec8f5c7d91f3b17e99cd9e79195bc5d9bb003a8623395896212ad682e1cd3f8a830fc6befd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
